server:
  port: 18666

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG

application:
  bluos:
    host: 192.168.1.7
    port: 11000
    timeout: 100
    excludedServices:
      - Spotify
  scrobblers:
    lastfm:
      apiUrl: https://ws.audioscrobbler.com/2.0
      authUrl: https://www.last.fm/api/auth
      enabled: true
      apiKey: 0aeed2d83c2c786a53ef7529bb833863
      sharedSecret: e5925cc6e70637f39b563e1cf32efade
      sessionKey: jPrakWsD2wUZCTO7UyP6rtDGxGDRjg7X